export const ErrorCodes = {
  // Common Errors
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Processing Errors
  OPENCV_LOAD_FAILED: 'OPENCV_LOAD_FAILED',
  WORKER_INIT_FAILED: 'WORKER_INIT_FAILED',
  PAGE_RENDER_FAILED: 'PAGE_RENDER_FAILED',
  PROCESSING_FAILED: 'PROCESSING_FAILED',
  EXPORT_FAILED: 'EXPORT_FAILED',
  MEMORY_LIMIT_EXCEEDED: 'MEMORY_LIMIT_EXCEEDED',
  PROCESSING_CANCELLED: 'PROCESSING_CANCELLED',

  // File Errors
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_TYPE_INVALID: 'FILE_TYPE_INVALID',
  PDF_ENCRYPTED: 'PDF_ENCRYPTED',
  PDF_CORRUPT: 'PDF_CORRUPT',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
