import { ProcessingConfig, ProcessingMode } from '../types/processing';

export const DEFAULT_CONFIG: ProcessingConfig = {
  mode: 'light-clean',
  dpi: 200,
  jpegQuality: 85,
  grayscale: true,
  gamma: 1.0,
  contrast: 1.2,
  thresholdBlockSize: 41,
  thresholdC: 7,
  blurKernelSize: 3,
  blurType: 'gaussian',
  morphologyKernelSize: 2,
  morphType: 'open',
  normKernelSize: 25,
  enableNoiseReduction: true,
  enableDeskew: false,
  enableBackgroundNorm: true,
  enableThresholding: true,
  enableMorphology: true,
};

export const MODE_CONFIGS: Record<Exclude<ProcessingMode, 'custom'>, Partial<ProcessingConfig>> = {
  'light-clean': {
    grayscale: false,
    gamma: 1.1,
    contrast: 1.1,
    blurType: 'gaussian',
    blurKernelSize: 3,
    normKernelSize: 35,
    enableBackgroundNorm: true,
    enableThresholding: false,
    enableMorphology: false,
    jpegQuality: 90,
  },
  'strong-background-removal': {
    grayscale: true,
    gamma: 0.8,
    contrast: 1.4,
    blurType: 'gaussian',
    blurKernelSize: 3,
    normKernelSize: 25,
    enableBackgroundNorm: true,
    enableThresholding: true,
    thresholdBlockSize: 41,
    thresholdC: 8,
    enableMorphology: false,
    jpegQuality: 85,
  },
  'text-contrast-boost': {
    grayscale: true,
    gamma: 0.6,
    contrast: 1.6,
    blurType: 'gaussian',
    blurKernelSize: 3,
    normKernelSize: 21,
    enableBackgroundNorm: true,
    enableThresholding: true,
    thresholdBlockSize: 41,
    thresholdC: 7,
    enableMorphology: false,
    jpegQuality: 90,
  },
  'print-optimized': {
    grayscale: true,
    gamma: 0.8,
    contrast: 1.4,
    blurType: 'gaussian',
    blurKernelSize: 3,
    normKernelSize: 21,
    enableBackgroundNorm: true,
    enableThresholding: true,
    thresholdBlockSize: 41,
    thresholdC: 9,
    enableMorphology: false,
    jpegQuality: 85,
    dpi: 300,
  },
  'heavy-noise-reduction': {
    grayscale: true,
    gamma: 0.9,
    contrast: 1.2,
    blurType: 'median',
    blurKernelSize: 5,
    normKernelSize: 25,
    enableBackgroundNorm: true,
    enableThresholding: true,
    thresholdBlockSize: 41,
    thresholdC: 7,
    enableMorphology: true,
    morphologyKernelSize: 2,
    morphType: 'close',
    jpegQuality: 85,
    dpi: 200,
  },
  'color-preservation': {
    grayscale: false,
    gamma: 0.9,
    contrast: 1.2,
    blurType: 'gaussian',
    blurKernelSize: 3,
    normKernelSize: 41,
    enableBackgroundNorm: true,
    enableThresholding: false,
    enableMorphology: false,
    jpegQuality: 95,
  },
};
